name: Java CI with Maven

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "dev" ]

env:
  DOCKER_IMAGE: fiveguys
  DOCKER_TAG: 0.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Gradle
        run: |
          cd innout
          ./gradlew build

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{secrets.DOCKER_USERNAME}}/$DOCKER_IMAGE
          tags: $DOCKER_TAG
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
