name: Java CI with Gradle

on:
  push:
    branches: [ "main"]

  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: fiveguys

  DOCKER_TAG: 1.3

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: |
        cd innout
        chmod +x ./gradlew

    - name: Build with Gradle
      run: |
        cd innout
        ./gradlew clean build -x test
      # Ensure Gradle generates JAR files here

    - name: List build/libs contents
      run: |
        cd innout
        ls -la build/libs
        # Check if the JAR file is created

        cache: maven
    - name: Build with Gradle
      run: |
        cd innout
        ./gradlew build



    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{secrets.DOCKER_USERNAME}}/$DOCKER_IMAGE
        tags: $DOCKER_TAG
        registry: docker.io

        dockerfile: innout/Dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}